version: '3.4'

services:
  redis:
    image: redis
    restart: always
    command: redis-server

  marketdataservice:
    image: marketdataservice
    build:
      context: .
      dockerfile: feldspar/MarketDataService/Dockerfile
    environment:
      - FELDSPAR_REDIS_CONNECTION=redis
      - FELDSPAR_ALPHAVANTAGE_BASE_URI=https://www.alphavantage.co
      - FELDSPAR_ALPHAVANTAGE_API_KEY
    depends_on:
      - redis

  middletier:
    image: middletier
    build:
      context: feldspar/middle_tier
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      FELDSPAR_REDIS_CONNECTION: redis
    depends_on:
      - redis

  web:
    image: web
    build:
      context: feldspar/web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    depends_on:
      - middletier
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]