version: '3.4'

services:
  redis:
    image: redis
    restart: always
    command: redis-server

  marketdataservice:
    image: feldspar.azurecr.io/marketdataservice:latest
    restart: always
    environment:
      - FELDSPAR_REDIS_CONNECTION=redis
      - FELDSPAR_ALPHAVANTAGE_BASE_URI=https://www.alphavantage.co
      - FELDSPAR_ALPHAVANTAGE_API_KEY=5COWD3JD8LTVLVCC
    depends_on:
      - redis

  middletier:
    image: feldspar.azurecr.io/middletier:latest
    restart: always
    environment:
      NODE_ENV: production
      FELDSPAR_REDIS_CONNECTION: redis
    depends_on:
      - redis

  web:
    image: feldspar.azurecr.io/web:latest
    restart: always
    environment:
      NODE_ENV: production
    depends_on:
      - middletier
    ports:
      - "80:80"
    command: ["nginx", "-g", "daemon off;"]